# Site settings
title: A stupid, innocent fool.
email: helyao@qq.com
description: Tips from a forgetful guy during daily life to awaken his memory. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://helyao.github.io" # the base hostname & protocol for your site
github_username:  helyao
wechat_username:  RyanYao123

# Build settings
markdown: kramdown
